title: EU Data Conferences
tag_text: EU Data Conferences
description: A list of upcoming data conferences in Europe. Missing one? Submit it!
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
markdown: kramdown
sass:
  style: compressed
include:
  - _headers